org: 8seczjohndpope
app: gifmaker

service: gifmaker

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - S3:PutObject
        - S3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  gifmaker:
    timeout: 60
    handler: handler.gifmaker
    events:
      - s3: 8seczgifmakerbucket
    layers:
      - {Ref: FfmpegLambdaLayer}
          
layers:
  ffmpeg:
    path: layer

custom:
  bucket: 8seczgifmakerbucket
